Automaton Core: connection::connection_handler Class Reference
connection::connection_handler Class Reference abstract
#include <connection.h>
Public Member Functions
virtual void on_connected (connection *c)=0
virtual void on_disconnected (connection *c)=0
virtual void on_error (connection *c, connection::error e)=0
virtual void on_message_received (connection *c, char *buffer, unsigned int bytes_read, unsigned int id)=0
virtual void on_message_sent (connection *c, unsigned int id, connection::error e)=0
Detailed Description
Handler class used to inform the client for events.
on_message_received will be invoked when message from remote peer was received; it passes the connection, representing from which peer was the message, and the message that was received.
on_message_sent will be invoked when a message was sent successfully using async_send.
on_connected will be invoked when the connection with the remote peer was established.
on_disconnected will be invoked when connection was closed/ destroyed by the local or the remote peer
on_error will be invoked when an error happens while listening or accepting.
Member Function Documentation
on_connected()
virtual void connection::connection_handler::on_connected (connection * c) pure virtual
Referenced by tcp_connection::connect(), and tcp_acceptor::start_accepting().
on_disconnected()
virtual void connection::connection_handler::on_disconnected (connection * c) pure virtual
Referenced by tcp_connection::async_read(), and tcp_connection::disconnect().
on_error()
virtual void connection::connection_handler::on_error (connection * c, connection::error e) pure virtual
Referenced by tcp_connection::async_read(), tcp_connection::connect(), and tcp_connection::disconnect().
on_message_received()
virtual void connection::connection_handler::on_message_received (connection * c, char * buffer, unsigned int bytes_read, unsigned int id) pure virtual
Referenced by tcp_connection::async_read().
on_message_sent()
virtual void connection::connection_handler::on_message_sent (connection * c, unsigned int id, connection::error e) pure virtual
Referenced by tcp_connection::async_send().
The documentation for this class was generated from the following file:
connection.h