Automaton Core: protobuf_schema Class Reference
protobuf_schema Class Reference
#include <protobuf_schema.h>
Public Member Functions
protobuf_schema ()
~protobuf_schema ()
int create_copy_message (int message_id)
void delete_message (int message_id)
bool deserialize_message (int message_id, const std::string &input)
void dump_enum (int enum_id, std::ostream &ostream_)
void dump_message_schema (int schema_id, std::ostream &ostream_)
int get_enum (int message_id, int field_tag)
std::string get_enum_field_type (int schema_id, int tag)
int get_enum_id (const std::string &enum_name)
int get_enum_value (int enum_id, const std::string &value_name)
std::vector< std::pair< std::string, int > > get_enum_values (int enum_id)
int get_enums_number ()
field_info get_field_info (int schema_id, int index)
int get_field_tag (int schema_id, const std::string &name)
std::string get_field_type (int schema_id, int tag)
int get_fields_number (int schema_id)
int32_t get_int32 (int message_id, int field_tag)
int get_message (int message_id, int field_tag)
std::string get_message_field_type (int schema_id, int tag)
int get_message_schema_id (int message_id)
int get_repeated_enum (int message_id, int field_tag, int index)
int get_repeated_field_size (int message_id, int field_tag)
int32_t get_repeated_int32 (int message_id, int field_tag, int index)
int get_repeated_message (int message_id, int field_tag, int index)
std::string get_repeated_string (int message_id, int field_tag, int index)
int get_schema_id (const std::string &schema_name)
std::string get_schema_name (int schema_id)
int get_schemas_number ()
std::string get_string (int message_id, int field_tag)
void import_schema_definition (schema_definition *schema, const std::string &name, const std::string &package)
void import_schema_from_string (const std::string &protocol, const std::string &name, const std::string &package)
bool is_repeated (int schema_id, int tag)
int new_message (int schema_id)
void register_self ()
bool serialize_message (int message_id, std::string *output)
void set_enum (int message_id, int field_tag, int value)
void set_int32 (int message_id, int field_tag, int32_t value)
void set_message (int message_id, int field_tag, int sub_message_id)
void set_repeated_enum (int message_id, int field_tag, int value, int index)
void set_repeated_int32 (int message_id, int field_tag, int32_t value, int index)
void set_repeated_message (int message_id, int field_tag, int sub_message_id, int index)
void set_repeated_string (int message_id, int field_tag, const std::string &value, int index)
void set_string (int message_id, int field_tag, const std::string &value)
std::string to_string (int message_id)
Static Public Attributes
static const std::map< google::protobuf::FieldDescriptor::CppType, schema::field_type > protobuf_ccptype_to_type
static const std::map< google::protobuf::FieldDescriptor::Type, schema::field_type > protobuf_type_to_type
static const std::map< schema::field_type, google::protobuf::FieldDescriptorProto_Type > type_to_protobuf_type
Additional Inherited Members
Public Types inherited from schema
typedef schema *(* factory_function_schema) ()
enum field_type {
unknown = 0, message_type = 1, enum_type = 2, string = 4,
int32 = 5
}
Static Public Member Functions inherited from schema
static schema * create (const std::string name)
static void register_factory (std::string name, factory_function_schema func)
Constructor & Destructor Documentation
protobuf_schema()
protobuf_schema::protobuf_schema ()
TODO(kari): Decide to forbid move & copy constructors.
Referenced by register_self().
{
   pool = google::protobuf::Arena::Create
       <google::protobuf::DescriptorPool>(&arena);
   dynamic_message_factory = google::protobuf::Arena::Create
       <google::protobuf::DynamicMessageFactory>(&arena, pool);
 }
~protobuf_schema()
protobuf_schema::~protobuf_schema ()
 {}
Member Function Documentation
create_copy_message()
int protobuf_schema::create_copy_message (int message_id) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   if (messages[message_id] == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   google::protobuf::Message* copy = messages[message_id]-> New();
   copy->CopyFrom(*messages[message_id]);
   return insert_message(copy);
 }
delete_message()
void protobuf_schema::delete_message (int message_id) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   delete messages[message_id];
   messages[message_id] = NULL;
   free_message_spots.push(message_id);
 }
deserialize_message()
bool protobuf_schema::deserialize_message (int message_id, const std::string & input) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL) {
     throw std::runtime_error("Unexpected error: No message");
   }
   return m->ParseFromString(input);  // TODO(kari): Handle errors.
 }
dump_enum()
void protobuf_schema::dump_enum (int enum_id, std::ostream & ostream_) virtual
following functions are too complicated for mvp.
Implements schema.
{
   if (enum_id < 0 || enum_id >= enums.size()) {
     throw std::out_of_range("No enum with id: " + std::to_string(enum_id));
   }
   const google::protobuf::EnumDescriptor* edesc = enums[enum_id];
   if (edesc == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   ostream_ << edesc->full_name() << " {" << std::endl;
   int values = edesc->value_count();
   for (int i = 0; i < values; i++) {
     const google::protobuf::EnumValueDescriptor* evdesc = edesc->value(i);
     ostream_ << '\t' << evdesc->name() << " = " << evdesc->number() <<
         std::endl;
   }
   ostream_ << "}" << std::endl;
 }
dump_message_schema()
void protobuf_schema::dump_message_schema (int schema_id, std::ostream & ostream_) virtual
Implements schema.
References protobuf_type_to_type.
{
   if (schema_id < 0 || schema_id >= schemas.size()) {
     throw std::out_of_range("No schema with id: " + std::to_string(schema_id));
   }
   const google::protobuf::Message* m = schemas[schema_id];
   const google::protobuf::Descriptor* desc = m->GetDescriptor();
   if (desc == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   ostream_ << "MessageType: " << desc->full_name() << " {" << std::endl;
   ostream_ << "Fields: " << std::endl;
   int field_count = desc->field_count();
   for (int i = 0; i < field_count; i++) {
     const google::protobuf::FieldDescriptor* fd = desc->field(i);
     ostream_ << "\n\tName: " << fd->name() << std::endl;
     ostream_ << "\tType: ";
     if (fd->cpp_type() == google::protobuf::FieldDescriptor::CPPTYPE_MESSAGE) {
       ostream_ << "message type: " << fd->message_type()->full_name() <<
           std::endl;
     } else if (fd->cpp_type() ==
         google::protobuf::FieldDescriptor::CPPTYPE_ENUM) {
       ostream_ << "enum type: " << fd->enum_type()->full_name() << std::endl;
     } else {
       ostream_ << protobuf_type_to_type.at(fd->type()) << std::endl;
     }
     ostream_ << "\tRepeated: ";
     if (fd->is_repeated()) {
       ostream_ << "YES" << std::endl;
     } else {
       ostream_ << "NO" << std::endl;
     }
     ostream_ << "\tTag: " << fd->number() << std::endl << std::endl;
   }
   ostream_ << "\n}" << std::endl;
 }
get_enum()
int protobuf_schema::get_enum (int message_id, int field_tag) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
       throw std::out_of_range("No message with id: " +
           std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
      ->FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->is_repeated()) {
     throw std::invalid_argument("Field is repeated");
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_ENUM) {
     throw std::invalid_argument("Field is not enum");
   }
   return m->GetReflection()->GetEnumValue(*m, fdesc);
 }
get_enum_field_type()
std::string protobuf_schema::get_enum_field_type (int schema_id, int tag) virtual
Implements schema.
{
   if (schema_id < 0 || schema_id >= schemas.size()) {
     throw std::out_of_range("No schema with id: " + std::to_string(schema_id));
   }
   if (schemas[schema_id]->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc =
       schemas[schema_id]->GetDescriptor()->FindFieldByNumber(field_tag);
   if (fdesc) {
     if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_ENUM) {
       throw std::invalid_argument("Field is not enum");
     }
     return fdesc->enum_type()->full_name();
   }
   throw std::invalid_argument("No field with tag: " + field_tag);
 }
get_enum_id()
int protobuf_schema::get_enum_id (const std::string & enum_name) virtual
Implements schema.
{
   if (enums_names.find(enum_name) == enums_names.end()) {
     throw std::invalid_argument("No enum '" + enum_name + '\'');
   }
   return enums_names[enum_name];
 }
get_enum_value()
int protobuf_schema::get_enum_value (int enum_id, const std::string & value_name) virtual
Implements schema.
{
   if (enum_id < 0 || enum_id >= enums.size()) {
     throw std::out_of_range("No enum with id: " + std::to_string(enum_id));
   }
   if (enums[enum_id] == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::EnumValueDescriptor* evd =
       enums[enum_id]->FindValueByName(value_name);
   if (evd == NULL) {
     throw std::invalid_argument("No enum value " + value_name);
   }
   return evd->number();
 }
get_enum_values()
std::vector< std::pair< std::string, int > > protobuf_schema::get_enum_values (int enum_id) virtual
Implements schema.
                    {
   if (enum_id < 0 || enum_id >= enums.size()) {
     throw std::out_of_range("No enum with id: " + std::to_string(enum_id));
   }
   std::vector<std::pair<std::string, int> > result;
   const google::protobuf::EnumDescriptor* edesc = enums[enum_id];
   if (edesc == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   int values = edesc->value_count();
   for (int i = 0; i < values; i++) {
     const google::protobuf::EnumValueDescriptor* evdesc = edesc->value(i);
     result.push_back(std::make_pair(evdesc->name(), evdesc->number()));
   }
   return result;
 }
get_enums_number()
int protobuf_schema::get_enums_number () virtual
Implements schema.
{
   return enums.size();
 }
get_field_info()
schema::field_info protobuf_schema::get_field_info (int schema_id, int index) virtual
Implements schema.
References protobuf_ccptype_to_type.
                  {
   if (!(schema_id >= 0 && schema_id < schemas.size())) {
     throw std::out_of_range("No schema with id: " + std::to_string(schema_id));
   }
   const google::protobuf::Descriptor* desc =
       schemas[schema_id]->GetDescriptor();
   if (desc == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   if (index < 0 || index >= desc->field_count()) {
     throw std::out_of_range("No field with such index: " +
         std::to_string(index));
   }
   const google::protobuf::FieldDescriptor* fdesc = desc->field(index);
   field_type type;
   std::string full_type = "";
   if (fdesc->cpp_type() == google::protobuf::FieldDescriptor::CPPTYPE_MESSAGE) {
     full_type = fdesc->message_type()->full_name();
     type = field_type::message_type;
   } else if (fdesc->cpp_type() ==
       google::protobuf::FieldDescriptor::CPPTYPE_ENUM) {
     full_type = fdesc->enum_type()->full_name();
     type = field_type::enum_type;
   } else {
     type = protobuf_ccptype_to_type.at(fdesc->cpp_type());
   }
   return field_info(fdesc->number(), type, fdesc->name(), full_type,
       fdesc->is_repeated());
 }
get_field_tag()
int protobuf_schema::get_field_tag (int schema_id, const std::string & name) virtual
Implements schema.
{
   if (schema_id < 0 || schema_id >= schemas.size()) {
     throw std::out_of_range("No schema with id: " + std::to_string(schema_id));
   }
   if (schemas[schema_id]->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc =
       schemas[schema_id]->GetDescriptor()->FindFieldByName(name);
   if (fdesc) {
     return fdesc->number();
   }
   throw std::invalid_argument("No field with name: " + name);
 }
get_field_type()
std::string protobuf_schema::get_field_type (int schema_id, int tag) virtual
Implements schema.
{
   if (schema_id < 0 || schema_id >= schemas.size()) {
     throw std::out_of_range("No schema with id: " + std::to_string(schema_id));
   }
   if (schemas[schema_id]->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc =
       schemas[schema_id]->GetDescriptor()->FindFieldByNumber(tag);
   if (fdesc) {
     return fdesc->cpp_type_name();
   }
   throw std::invalid_argument("No field with tag: " + std::to_string(tag));
 }
get_fields_number()
int protobuf_schema::get_fields_number (int schema_id) virtual
Implements schema.
{
   if (!(schema_id >= 0 && schema_id < schemas.size())) {
     throw std::out_of_range("No schema with id: " + std::to_string(schema_id));
   }
   const google::protobuf::Descriptor* desc =
       schemas[schema_id]->GetDescriptor();
   if (desc == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   return desc->field_count();
 }
get_int32()
int32_t protobuf_schema::get_int32 (int message_id, int field_tag) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
       throw std::out_of_range("No message with id: " +
           std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
      ->FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->is_repeated()) {
     throw std::invalid_argument("Field is repeated");
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_INT32) {
     throw std::invalid_argument("Field is not int32");
   }
   return m->GetReflection()->GetInt32(*m, fdesc);
 }
get_message()
int protobuf_schema::get_message (int message_id, int field_tag) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->is_repeated()) {
     throw std::invalid_argument("Field is repeated");
   }
   const google::protobuf::Reflection* reflect = m->GetReflection();
     if (fdesc->cpp_type() !=
         google::protobuf::FieldDescriptor::CPPTYPE_MESSAGE) {
     throw std::invalid_argument("Field is not message");
   }
   // name resolution need to be done
   // to get Dynamic Message Factory of the class containing the sub message
   const google::protobuf::Message* original = &reflect->GetMessage(*m, fdesc);
   google::protobuf::Message* copy = original->New();
   copy->CopyFrom(*original);
   return insert_message(copy);
 }
get_message_field_type()
std::string protobuf_schema::get_message_field_type (int schema_id, int tag) virtual
Implements schema.
                      {
   if (schema_id < 0 || schema_id >= schemas.size()) {
     throw std::out_of_range("No schema with id: " + std::to_string(schema_id));
   }
   if (schemas[schema_id]->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc =
       schemas[schema_id]->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc) {
     if (fdesc->cpp_type() !=
         google::protobuf::FieldDescriptor::CPPTYPE_MESSAGE) {
       throw std::invalid_argument("Field is not message");
     }
     return fdesc->message_type()->full_name();
   }
   throw std::invalid_argument("No field with tag: " + field_tag);
 }
get_message_schema_id()
int protobuf_schema::get_message_schema_id (int message_id) virtual
Implements schema.
References get_schema_id().
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: " +
         std::to_string(message_id));
   }
   if (messages[message_id] == NULL) {
     throw std::runtime_error("Unexpected error: No message");
   }
   return get_schema_id(messages[message_id]->GetTypeName());
 }
get_repeated_enum()
int protobuf_schema::get_repeated_enum (int message_id, int field_tag, int index) virtual
Implements schema.
                  {
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_ENUM) {
     throw std::invalid_argument("Field is not enum");
   }
   if (!(fdesc->is_repeated())) {
     throw std::invalid_argument("Field is not repeated");
   }
   const google::protobuf::Reflection* reflect = m->GetReflection();
   if (index >= 0 && index < reflect->FieldSize(*m, fdesc)) {
     return m->GetReflection()->GetRepeatedEnumValue(*m, fdesc, index);
   } else {
     throw std::out_of_range("Index out of range: " + std::to_string(index));
   }
 }
get_repeated_field_size()
int protobuf_schema::get_repeated_field_size (int message_id, int field_tag) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (!(fdesc->is_repeated())) {
     throw std::invalid_argument("Field is not repeated");
   }
   return m->GetReflection()->FieldSize(*m, fdesc);
 }
get_repeated_int32()
int32_t protobuf_schema::get_repeated_int32 (int message_id, int field_tag, int index) virtual
Implements schema.
                  {
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_INT32) {
     throw std::invalid_argument("Field is not int32");
   }
   if (!(fdesc->is_repeated())) {
     throw std::invalid_argument("Field is not repeated");
   }
   const google::protobuf::Reflection* reflect = m->GetReflection();
   if (index >= 0 && index < reflect->FieldSize(*m, fdesc)) {
     return reflect->GetRepeatedInt32(*m, fdesc, index);
   } else {
     throw std::out_of_range("Index out of range: " + std::to_string(index));
   }
 }
get_repeated_message()
int protobuf_schema::get_repeated_message (int message_id, int field_tag, int index) virtual
Implements schema.
                  {
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_MESSAGE) {
     throw std::invalid_argument("Field is not message");
   }
   if (!(fdesc->is_repeated())) {
     throw std::invalid_argument("Field is not repeated");
   }
   const google::protobuf::Reflection* reflect = m->GetReflection();
   if (index >= 0 && index < reflect->FieldSize(*m, fdesc)) {
     const google::protobuf::Message* original =
         &reflect->GetRepeatedMessage(*m, fdesc, index);
     google::protobuf::Message* copy = original->New();
     copy->CopyFrom(*original);
     return insert_message(copy);
   } else {
     throw std::out_of_range("Index out of range: " + std::to_string(index));
   }
 }
get_repeated_string()
std::string protobuf_schema::get_repeated_string (int message_id, int field_tag, int index) virtual
Implements schema.
                  {
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_STRING) {
     throw std::invalid_argument("Field is not string");
   }
   if (!(fdesc->is_repeated())) {
     throw std::invalid_argument("Field is not repeated");
   }
   const google::protobuf::Reflection* reflect = m->GetReflection();
   if (index >= 0 && index < reflect->FieldSize(*m, fdesc)) {
     return reflect->GetRepeatedString(*m, fdesc, index);
   } else {
     throw std::out_of_range("Index out of range: " + std::to_string(index));
   }
 }
get_schema_id()
int protobuf_schema::get_schema_id (const std::string & schema_name) virtual
Implements schema.
Referenced by get_message_schema_id().
{
   if (schemas_names.find(message_name) == schemas_names.end()) {
     throw std::invalid_argument("No schema '" + message_name + '\'');
   }
   return schemas_names[message_name];
 }
get_schema_name()
std::string protobuf_schema::get_schema_name (int schema_id) virtual
Implements schema.
{
   if (schema_id < 0 || schema_id >= schemas.size()) {
     throw std::out_of_range("No schema with id: " + std::to_string(schema_id));
   }
   if (schemas[schema_id] == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   return schemas[schema_id]->GetTypeName();
 }
get_schemas_number()
int protobuf_schema::get_schemas_number () virtual
Implements schema.
{
   return schemas.size();
 }
get_string()
std::string protobuf_schema::get_string (int message_id, int field_tag) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
       throw std::out_of_range("No message with id: " +
           std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->is_repeated()) {
     throw std::invalid_argument("Field is repeated");
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_STRING) {
     throw std::invalid_argument("Field is not string");
   }
   return m->GetReflection()->GetString(*m, fdesc);
 }
import_schema_definition()
void protobuf_schema::import_schema_definition (schema_definition * schema, const std::string & name, const std::string & package) virtual
Implements schema.
{
   if (schema == NULL) {
     throw std::runtime_error("Schema reference is NULL");
   }
   // TODO(kari): schema need to be protobuf_schema
   import_from_file_proto(reinterpret_cast<protobuf_schema_definition*>(schema)
       ->get_descriptor(), name, package);
 }
import_schema_from_string()
void protobuf_schema::import_schema_from_string (const std::string & protocol, const std::string & name, const std::string & package) virtual
Implements schema.
References io_error_collector::get_all_errors(), and io_error_collector::get_number_errors().
{
   google::protobuf::FileDescriptorProto* fileproto =
       google::protobuf::Arena::Create<
       google::protobuf::FileDescriptorProto>(&arena);
   std::istringstream stream(proto_def);
   google::protobuf::io::IstreamInputStream is(&stream);
   google::protobuf::io::Tokenizer tok(&is, &io_error_collector_);
   if (io_error_collector_.get_number_errors() > 0) {
     throw std::runtime_error(io_error_collector_.get_all_errors());
   }
   google::protobuf::compiler::Parser parser;
   parser.RecordErrorsTo(&io_error_collector_);
   if (io_error_collector_.get_number_errors() > 0) {
     throw std::runtime_error(io_error_collector_.get_all_errors());
   }
   parser.Parse(&tok, fileproto);  // TODO(kari): Handle errors.
   if (io_error_collector_.get_number_errors() > 0) {
     throw std::runtime_error("Errors while parsing:\n" +
         io_error_collector_.get_all_errors());
   }
   import_from_file_proto(fileproto, package, name);
 }
is_repeated()
bool protobuf_schema::is_repeated (int schema_id, int tag) virtual
Implements schema.
{
   if (!(schema_id >= 0 && schema_id < schemas.size())) {
     throw std::out_of_range("No schema with id: " + std::to_string(schema_id));
   }
   if (schemas[schema_id]->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc =
       schemas[schema_id]->GetDescriptor()->FindFieldByNumber(field_tag);
   if (fdesc) {
     return fdesc->is_repeated();
   }
   throw std::invalid_argument("No field with tag: " + field_tag);
 }
new_message()
int protobuf_schema::new_message (int schema_id) virtual
Implements schema.
{
   if (schema_id < 0 || schema_id >= schemas.size()) {
     throw std::out_of_range("No schema with id: " + std::to_string(schema_id));
   }
   if (schemas[schema_id] == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   google::protobuf::Message* m = schemas[schema_id]-> New();
   return insert_message(m);
 }
register_self()
void protobuf_schema::register_self ()
References protobuf_schema(), and schema::register_factory().
{
   protobuf_schema::register_factory("protobuf", [] {
       return reinterpret_cast<schema*>(new protobuf_schema());
   });
 }
serialize_message()
bool protobuf_schema::serialize_message (int message_id, std::string * output) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (output == NULL) {
     throw std::invalid_argument("No output provided");
   }
   if (m == NULL) {
     throw std::runtime_error("Unexpected error: No message");
   }
   return m->SerializeToString(output);  // TODO(kari): Handle errors.
 }
set_enum()
void protobuf_schema::set_enum (int message_id, int field_tag, int value) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
      ->FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->is_repeated()) {
     throw std::invalid_argument("Field is repeated");
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_ENUM) {
     throw std::invalid_argument("Field is not enum");
   }
   const google::protobuf::EnumDescriptor* edesc = fdesc->enum_type();
   if (edesc->FindValueByNumber(value) == NULL) {
     throw std::invalid_argument("Enum doesn't have value: " +
         std::to_string(value));
   }
   m->GetReflection()->SetEnumValue(m, fdesc, value);
 }
set_int32()
void protobuf_schema::set_int32 (int message_id, int field_tag, int32_t value) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
      ->FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->is_repeated()) {
     throw std::invalid_argument("Field is repeated");
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_INT32) {
     throw std::invalid_argument("Field is not int32");
   }
   m->GetReflection()->SetInt32(m, fdesc, value);
 }
set_message()
void protobuf_schema::set_message (int message_id, int field_tag, int sub_message_id) virtual
Implements schema.
References schema::message_type.
                       {
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   if (!(sub_message_id >= 0 && sub_message_id < messages.size())) {
     throw std::out_of_range("No sub message with id: " +
         std::to_string(sub_message_id));
   }  // throw
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error: No message");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->is_repeated()) {
     throw std::invalid_argument("Field is repeated");
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_MESSAGE) {
     throw std::invalid_argument("Field is not message");
   }
   if (messages[sub_message_id] == NULL || messages[sub_message_id]->
         GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error: No message");
   }
   std::string message_type = fdesc->message_type()->full_name();  // Error
   std::string sub_message_type = messages[sub_message_id]->
       GetDescriptor()->full_name();
   if (message_type.compare(sub_message_type)) {
     throw std::invalid_argument("Type of the given sub message (which is <" +
         sub_message_type + ">) doesn't match the field type (which is <" +
         message_type + ">)");
   }
   const google::protobuf::Reflection* reflect = m->GetReflection();
   // creates copy of the sub message so that the field doesnt change if you
   // change the message outside
   google::protobuf::Message* copy = messages[sub_message_id]->New(&arena);
   copy->CopyFrom(*messages[sub_message_id]);
   reflect->SetAllocatedMessage(m, copy, fdesc);
 }
set_repeated_enum()
void protobuf_schema::set_repeated_enum (int message_id, int field_tag, int value, int index = -1) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
      ->FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_ENUM) {
     throw std::invalid_argument("Field is not enum");
   }
   if (!(fdesc->is_repeated())) {
     throw std::invalid_argument("Field is not repeated");
   }
   const google::protobuf::EnumDescriptor* edesc = fdesc->enum_type();
   if (edesc->FindValueByNumber(value) == NULL) {
     throw std::invalid_argument("Enum doesn't have value: " +
         std::to_string(value));
   }
   const google::protobuf::Reflection* reflect = m->GetReflection();
   if (index >= 0 && index < reflect->FieldSize(*messages[message_id], fdesc)) {
     reflect->SetRepeatedEnumValue(m, fdesc, index, value);
   } else {
     reflect->AddEnumValue(m, fdesc, value);
   }
 }
set_repeated_int32()
void protobuf_schema::set_repeated_int32 (int message_id, int field_tag, int32_t value, int index = -1) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
      ->FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_INT32) {
     throw std::invalid_argument("Field is not int32");
   }
   if (!(fdesc->is_repeated())) {
     throw std::invalid_argument("Field is not repeated");
   }
   const google::protobuf::Reflection* reflect = m->GetReflection();
   if (index >= 0 && index < reflect->FieldSize(*messages[message_id], fdesc)) {
     reflect->SetRepeatedInt32(m, fdesc, index, value);
   } else {
     reflect->AddInt32(m, fdesc, value);
   }
 }
set_repeated_message()
void protobuf_schema::set_repeated_message (int message_id, int field_tag, int sub_message_id, int index = -1) virtual
Implements schema.
References schema::message_type.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   if (!(sub_message_id >= 0 && sub_message_id < messages.size())) {
     throw std::out_of_range("No sub message with id: " +
         std::to_string(sub_message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_MESSAGE) {
     throw std::invalid_argument("Field is not message");
   }
   if (!(fdesc->is_repeated())) {
     throw std::invalid_argument("Field is not repeated");
   }
   if (messages[sub_message_id] == NULL || messages[sub_message_id]->
         GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   std::string message_type = fdesc->message_type()->full_name();  // Error
   std::string sub_message_type = messages[sub_message_id]->
       GetDescriptor()->full_name();
   if (message_type.compare(sub_message_type)) {
     throw std::invalid_argument("Type of the given sub message (which is <" +
         sub_message_type + ">) doesn't match the field type (which is <" +
         message_type + ">)");
   }
   const google::protobuf::Reflection* reflect = m->GetReflection();
   if (index >= 0 && index < reflect->FieldSize(*m, fdesc)) {
     google::protobuf::Message* sub_m = messages[sub_message_id];
     reflect->MutableRepeatedMessage(m, fdesc, index)->CopyFrom(*sub_m);
   } else {
     google::protobuf::Message* copy = messages[sub_message_id]-> New(&arena);
     copy->CopyFrom(*messages[sub_message_id]);
     reflect->AddAllocatedMessage(m, fdesc, copy);
   }
 }
set_repeated_string()
void protobuf_schema::set_repeated_string (int message_id, int field_tag, const std::string & value, int index = -1) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_STRING) {
     throw std::invalid_argument("Field is not string");
   }
   if (!(fdesc->is_repeated())) {
     throw std::invalid_argument("Field is not repeated");
   }
   const google::protobuf::Reflection* reflect = m->GetReflection();
   if (index >= 0 && index < reflect->FieldSize(*messages[message_id], fdesc)) {
     reflect->SetRepeatedString(m, fdesc, index, value);
   } else {
     reflect->AddString(m, fdesc, value);
   }
 }
set_string()
void protobuf_schema::set_string (int message_id, int field_tag, const std::string & value) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   google::protobuf::Message* m = messages[message_id];
   if (m == NULL || m->GetDescriptor() == NULL) {
     throw std::runtime_error("Unexpected error: No message");
   }
   const google::protobuf::FieldDescriptor* fdesc = m->GetDescriptor()
       -> FindFieldByNumber(field_tag);
   if (fdesc == NULL) {
     throw std::invalid_argument("No field with tag: " +
         std::to_string(field_tag));
   }
   if (fdesc->is_repeated()) {
     throw std::invalid_argument("Field is repeated");
   }
   if (fdesc->cpp_type() != google::protobuf::FieldDescriptor::CPPTYPE_STRING) {
     throw std::invalid_argument("Field is not string");
   }
   m->GetReflection()->SetString(m, fdesc, value);
 }
to_string()
std::string protobuf_schema::to_string (int message_id) virtual
Implements schema.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   if (messages[message_id] == NULL) {
     throw std::runtime_error("Unexpected error: No message");
   }
   return messages[message_id]->DebugString();
 }
Member Data Documentation
protobuf_ccptype_to_type
const std::map< google::protobuf::FieldDescriptor::CppType, schema::field_type > protobuf_schema::protobuf_ccptype_to_type static
Initial value:
{
  {google::protobuf::FieldDescriptor::CPPTYPE_STRING, schema::string},
  {google::protobuf::FieldDescriptor::CPPTYPE_INT32, schema::int32},
  {google::protobuf::FieldDescriptor::CPPTYPE_ENUM, schema::enum_type},
  {google::protobuf::FieldDescriptor::CPPTYPE_MESSAGE, schema::message_type}
}
Referenced by get_field_info().
protobuf_type_to_type
const std::map< google::protobuf::FieldDescriptor::Type, schema::field_type > protobuf_schema::protobuf_type_to_type static
Initial value:
{
  {google::protobuf::FieldDescriptor::Type::TYPE_STRING, schema::string},
  {google::protobuf::FieldDescriptor::Type::TYPE_INT32, schema::int32},
  {google::protobuf::FieldDescriptor::Type::TYPE_ENUM, schema::enum_type},
  {google::protobuf::FieldDescriptor::Type::TYPE_MESSAGE,
    schema::message_type}
}
Referenced by dump_message_schema().
type_to_protobuf_type
const std::map< schema::field_type, google::protobuf::FieldDescriptorProto_Type > protobuf_schema::type_to_protobuf_type static
Initial value:
{
  {schema::string, google::protobuf::FieldDescriptorProto_Type_TYPE_STRING},
  {schema::int32, google::protobuf::FieldDescriptorProto_Type_TYPE_INT32},
  {schema::enum_type, google::protobuf::FieldDescriptorProto_Type_TYPE_ENUM},
  {schema::message_type,
      google::protobuf::FieldDescriptorProto_Type_TYPE_MESSAGE}
}
Referenced by protobuf_schema_definition::add_scalar_field().
The documentation for this class was generated from the following files:
protobuf_schema.h
protobuf_schema.cc