Automaton Core: hash_transformation Class Reference
hash_transformation Class Reference abstract
#include <hash_transformation.h>
Public Types
typedef hash_transformation *(* factory_function_type) ()
Public Member Functions
virtual void calculate_digest (const unsigned char *input, const size_t length, unsigned char *digest)
virtual unsigned int digest_size () const =0
virtual void final (unsigned char *digest)=0
virtual void restart ()=0
virtual void update (const unsigned char *input, const size_t length)=0
Static Public Member Functions
static hash_transformation * create (const std::string name)
static void register_factory (std::string name, factory_function_type func)
Member Typedef Documentation
factory_function_type
typedef hash_transformation*(* hash_transformation::factory_function_type) ()
Member Function Documentation
calculate_digest()
void hash_transformation::calculate_digest (const unsigned char * input, const size_t length, unsigned char * digest) virtual
Reimplemented in RIPEMD160_cryptopp, SHA256_cryptopp, SHA512_cryptopp, Keccak_256_cryptopp, and SHA3_256_cryptopp.
References update().
create()
hash_transformation * hash_transformation::create (const std::string name) static
digest_size()
virtual unsigned int hash_transformation::digest_size () const pure virtual
Implemented in RIPEMD160_cryptopp, SHA256_cryptopp, SHA512_cryptopp, Keccak_256_cryptopp, and SHA3_256_cryptopp.
Referenced by dummy_state::get_node_hash(), and state_impl::hash_size().
final()
virtual void hash_transformation::final (unsigned char * digest) pure virtual
Implemented in RIPEMD160_cryptopp, SHA256_cryptopp, SHA512_cryptopp, Keccak_256_cryptopp, and SHA3_256_cryptopp.
Referenced by dummy_state::get_node_hash().
register_factory()
void hash_transformation::register_factory (std::string name, factory_function_type func) static
Referenced by SHA3_256_cryptopp::register_self(), Keccak_256_cryptopp::register_self(), RIPEMD160_cryptopp::register_self(), SHA256_cryptopp::register_self(), and SHA512_cryptopp::register_self().
restart()
virtual void hash_transformation::restart () pure virtual
Implemented in RIPEMD160_cryptopp, SHA256_cryptopp, SHA512_cryptopp, Keccak_256_cryptopp, and SHA3_256_cryptopp.
Referenced by dummy_state::get_node_hash().
update()
virtual void hash_transformation::update (const unsigned char * input, const size_t length) pure virtual
Implemented in RIPEMD160_cryptopp, SHA256_cryptopp, SHA512_cryptopp, Keccak_256_cryptopp, and SHA3_256_cryptopp.
Referenced by calculate_digest(), and dummy_state::get_node_hash().
The documentation for this class was generated from the following files:
hash_transformation.h
hash_transformation.cc