Automaton Core: Keccak_256_cryptopp Class Reference
Keccak_256_cryptopp Class Reference
#include <Keccak_256_cryptopp.h>
Public Member Functions
Keccak_256_cryptopp ()
void calculate_digest (const unsigned char *input, const size_t length, unsigned char *digest)
unsigned int digest_size () const
void final (unsigned char *digest)
void restart ()
void update (const unsigned char *input, const size_t length)
Static Public Member Functions
static bool register_self ()
Static Public Member Functions inherited from hash_transformation
static hash_transformation * create (const std::string name)
static void register_factory (std::string name, factory_function_type func)
Additional Inherited Members
Public Types inherited from hash_transformation
typedef hash_transformation *(* factory_function_type) ()
Constructor & Destructor Documentation
Keccak_256_cryptopp()
Keccak_256_cryptopp::Keccak_256_cryptopp ()
Referenced by register_self().
Member Function Documentation
calculate_digest()
void Keccak_256_cryptopp::calculate_digest (const unsigned char * input, const size_t length, unsigned char * digest) virtual
Reimplemented from hash_transformation.
digest_size()
unsigned int Keccak_256_cryptopp::digest_size () const virtual
Implements hash_transformation.
final()
void Keccak_256_cryptopp::final (unsigned char * digest) virtual
Implements hash_transformation.
register_self()
bool Keccak_256_cryptopp::register_self () static
References Keccak_256_cryptopp(), and hash_transformation::register_factory().
restart()
void Keccak_256_cryptopp::restart () virtual
Implements hash_transformation.
update()
void Keccak_256_cryptopp::update (const unsigned char * input, const size_t length) virtual
Implements hash_transformation.
The documentation for this class was generated from the following files:
Keccak_256_cryptopp.h
Keccak_256_cryptopp.cc