Automaton Core: tcp_acceptor Class Reference
tcp_acceptor Class Reference
#include <tcp_implementation.h>
Public Member Functions
tcp_acceptor (const std::string &address, acceptor_handler *handler_, connection::connection_handler *connections_handler)
~tcp_acceptor ()
void start_accepting ()
Additional Inherited Members
Public Types inherited from acceptor
typedef acceptor *(* factory_function) (const std::string &address, acceptor_handler *handler_, connection::connection_handler *connections_handler)
Static Public Member Functions inherited from acceptor
static acceptor * create (const std::string &type, const std::string &address, acceptor_handler *handler_, connection::connection_handler *connections_handler)
static void register_acceptor_type (const std::string &type, factory_function func)
Protected Member Functions inherited from acceptor
acceptor (acceptor_handler *handler_)
Protected Attributes inherited from acceptor
acceptor_handler * handler
Constructor & Destructor Documentation
tcp_acceptor()
tcp_acceptor::tcp_acceptor (const std::string & address, acceptor_handler * handler_, connection::connection_handler * connections_handler)
Constructor. Connections_handler will be passed to the connection constructor when new connection is accepted and created. It will also be used to call its on_connected() method.
References asio_io_service.
                                                                  :
     acceptor(handler_), asio_acceptor{asio_io_service},
     accepted_connections_handler(connections_handler_) {
   boost::asio::ip::tcp::resolver resolver{asio_io_service};
   boost::system::error_code boost_error_code;
   std::string ip, port;
   parse_address(address, &ip, &port);
   boost::asio::ip::tcp::resolver::query q{ip, port};
   boost::asio::ip::tcp::resolver::iterator it = resolver.resolve(q,
       boost_error_code);
   if (boost_error_code) {
     logging("Error (in acceptor constructor 0): " + boost_error_code.message());
     handler->on_error(connection::error::invalid_address);
   } else {
     boost::system::error_code ecc;
     asio_acceptor.open(((boost::asio::ip::tcp::endpoint)*it).protocol());
     asio_acceptor.bind(*it, ecc);
     if (ecc) {
       handler->on_error(connection::error::unknown);
       logging("Error (in acceptor constructor 1): " + ecc.message());
     } else {
       asio_acceptor.listen();
     }
   }
 }
~tcp_acceptor()
tcp_acceptor::~tcp_acceptor ()
Destructor.
{
   asio_acceptor.close();
 }
Member Function Documentation
start_accepting()
void tcp_acceptor::start_accepting () virtual
This function is called from the constructor to start asynchronous accepting. When a remote peer request to make a connection, handler's on_requested() method will be called, passing peer's address and waiting for confirmaton to accept or not. If on_requested() returns true, then a connection is created and its handler's on_connected() called. Acceptor's handler's on_connected will also be called and a pointer to the created connection passed. If an error occured while accepting, handler's on_error() will be called. TODO(kari): Decide what to do on error.
Implements acceptor.
References asio_io_service, acceptor::handler, logging(), acceptor::acceptor_handler::on_connected(), connection::connection_handler::on_connected(), acceptor::acceptor_handler::on_error(), acceptor::acceptor_handler::on_requested(), and tcp_initialized.
{
   if (tcp_initialized && asio_acceptor.is_open()) {
     asio_acceptor.async_accept(asio_io_service, [this]
         (const boost::system::error_code& boost_error_code,
         boost::asio::ip::tcp::socket socket_) {
        if (!boost_error_code) {
           boost::asio::ip::tcp::endpoint remote_endpoint =
               socket_.remote_endpoint();
           std::string remote_address = (remote_endpoint.address()).to_string() +
           ":" + std::to_string(remote_endpoint.port());
           bool accepted = handler->on_requested(remote_address);
           if (accepted) {
             tcp_connection* new_con = new tcp_connection(remote_address,
                 socket_, accepted_connections_handler);
             handler->on_connected(new_con, remote_address);
             if (accepted_connections_handler) {
               accepted_connections_handler->on_connected(new_con);
             }
           }
           start_accepting();
         } else {
           // TODO(kari): Handle errors
           logging("ERROR (in start_accepting()): " +
               boost_error_code.message());
           handler->on_error(connection::error::unknown);
           // TODO(kari): start listen again? depends on the errors
           // start_accepting();
         }
       });
   } else if (!tcp_initialized) {
     logging("ERROR (in start_accepting()): Not initialized");
     handler->on_error(connection::error::unknown);
     // TODO(kari): what to do here? needs to be connected
   } else {
     logging("ERROR (in start_accepting()): Acceptor closed");
     handler->on_error(connection::error::closed_by_peer);
   }
 }
The documentation for this class was generated from the following files:
tcp_implementation.h
tcp_implementation.cc