Automaton Core: dummy_state Class Reference
dummy_state Class Reference
#include <dummy_state.h>
Public Member Functions
dummy_state (hash_transformation *hash)
virtual void commit_changes ()
virtual void delete_node_tree (std::string path)
virtual void discard_changes ()
virtual std::string get (std::string key)
virtual std::vector< std::string > get_node_children (std::string path)
virtual std::string get_node_hash (std::string path)
virtual void set (std::string key, std::string value)
Public Member Functions inherited from state
virtual void delete_node_tree (const std::string &path)=0
virtual void erase (const std::string &path)=0
virtual std::string get (const std::string &key)=0
virtual std::vector< std::string > get_node_children (const std::string &path)=0
virtual std::string get_node_hash (const std::string &path)=0
virtual uint32_t hash_size ()=0
virtual void set (const std::string &key, const std::string &value)=0
Constructor & Destructor Documentation
dummy_state()
dummy_state::dummy_state (hash_transformation * hash) explicit
                                                    : hash(hash) {
   google::InstallFailureSignalHandler();
 }
Member Function Documentation
commit_changes()
void dummy_state::commit_changes () virtual
Implements state.
{
   LOG(INFO) << "COMMIT " << pending_changes.size() << " PENDING CHANGES"
       << std::endl;
   for (auto kv : pending_changes) {
     auto& key = kv.first;
     auto& value = kv.second;
     data.erase(key);
     if (value == "") {
       LOG(INFO) << "REMOVING " << key << std::endl;
     } else {
       LOG(INFO) << "ADDING " << key << ":" << value << std::endl;
       data.insert(kv);
     }
   }
   pending_changes.clear();
 }
delete_node_tree()
void dummy_state::delete_node_tree (std::string path) virtual
{
   auto start = data.lower_bound(path);
   auto end = data.upper_bound(path + "\xFF");
   for (auto it = start; it != end; it++) {
     LOG(INFO) << "DELETING FROM MAIN STATE " << it->first << std::endl;
     pending_changes.erase(it->first);
     pending_changes.insert(std::pair<std::string, std::string>(it->first, ""));
   }
   start = pending_changes.lower_bound(path);
   end = pending_changes.upper_bound(path + "\xFF");
   for (auto it = start; it != end; it++) {
     if (it->second != "") {
       LOG(INFO) << "DELETING FROM PENDING CHANGES " << it->first << std::endl;
       pending_changes.erase(it->first);
       pending_changes.insert(
           std::pair<std::string, std::string>(it->first, ""));
     }
   }
 }
discard_changes()
void dummy_state::discard_changes () virtual
Implements state.
{
   pending_changes.clear();
 }
get()
std::string dummy_state::get (std::string key) virtual
{
   if (pending_changes.count(key)) {
     return pending_changes.at(key);
   }
   if (data.count(key)) {
     return data.at(key);
   }
   return "";
 }
get_node_children()
std::vector< std::string > dummy_state::get_node_children (std::string path) virtual
{
   return std::vector<std::string>();
 }
get_node_hash()
std::string dummy_state::get_node_hash (std::string path) virtual
References hash_transformation::digest_size(), hash_transformation::final(), hash_transformation::restart(), and hash_transformation::update().
{
   LOG(INFO) << "SIZE: " << data.size() << std::endl;
   if (data.size() == 0) {
     return "";
   }
   hash->restart();
   for (auto kv : data) {
     hash->update((const unsigned char *)kv.first.c_str(), kv.first.size());
     hash->update((const unsigned char *)kv.second.c_str(), kv.second.size());
   }
   unsigned char * digest = new unsigned char[hash->digest_size()];
   hash->final(digest);
   std::string result((const char *)digest, hash->digest_size());
   delete[] digest;
   return result;
 }
set()
void dummy_state::set (std::string key, std::string value) virtual
{
   pending_changes.erase(key);
   pending_changes.insert(std::pair<std::string, std::string>(key, value));
 }
The documentation for this class was generated from the following files:
dummy_state.h
dummy_state.cc