Automaton Core: protobuf_schema_definition Class Reference
protobuf_schema_definition Class Reference
#include <protobuf_schema.h>
Public Member Functions
protobuf_schema_definition ()
~protobuf_schema_definition ()
void add_dependency (const std::string &schema_name)
void add_enum (int enum_id, int message_id)
void add_enum_field (schema::field_info field, int message_id)
void add_enum_value (int enum_id, const std::string &value_name, int value)
void add_message (int message_id)
void add_message_field (schema::field_info field, int message_id)
void add_nested_message (int message_id, int sub_message_id)
void add_scalar_field (schema::field_info field, int message_id)
int create_enum (const std::string &enum_name)
int create_message (const std::string &message_name)
google::protobuf::FileDescriptorProto * get_descriptor ()
void register_self ()
Additional Inherited Members
Public Types inherited from schema::schema_definition
typedef schema_definition *(* factory_function_schema_def) ()
Static Public Member Functions inherited from schema::schema_definition
static schema_definition * create (const std::string name)
static void register_factory (std::string name, factory_function_schema_def func)
Constructor & Destructor Documentation
protobuf_schema_definition()
protobuf_schema_definition::protobuf_schema_definition ()
Referenced by register_self().
{
   file_descriptor_proto = google::protobuf::Arena::Create<
       google::protobuf::FileDescriptorProto>(&arena);
   file_descriptor_proto->set_syntax("proto3");
 }
~protobuf_schema_definition()
protobuf_schema_definition::~protobuf_schema_definition ()
 {}
Member Function Documentation
add_dependency()
void protobuf_schema_definition::add_dependency (const std::string & schema_name) virtual
If this schema (schema A) depends on another one (schema B), it must be added here. Schema_name is the name that has been/will be given to the schema (B) on import (when schema::import_schema_definition() is called). Shema B should be imported before Schema A.
Implements schema::schema_definition.
                  {
   file_descriptor_proto->add_dependency(schema_name);
 }
add_enum()
void protobuf_schema_definition::add_enum (int enum_id, int message_id = -1) virtual
Implements schema::schema_definition.
           {
   if (enum_id < 0 || enum_id >= enums.size()) {
     throw std::out_of_range("No enum with id: " + std::to_string(enum_id));
   }
   if (enums[enum_id] == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   if (message_id == -1) {
     google::protobuf::EnumDescriptorProto* edp =
         file_descriptor_proto->add_enum_type();
     edp->CopyFrom(*enums[enum_id]);
   } else {
     if (message_id < 0 || message_id >= messages.size()) {
       throw std::out_of_range("No message with id: "
           + std::to_string(message_id));
     }
     if (messages[message_id] == NULL) {
       throw std::runtime_error("Unexpected error");
     }
     google::protobuf::DescriptorProto* dpr = messages[message_id];
     google::protobuf::EnumDescriptorProto* edp = dpr->add_enum_type();
     edp->CopyFrom(*enums[enum_id]);
   }
 }
add_enum_field()
void protobuf_schema_definition::add_enum_field (schema::field_info field, int message_id) virtual
Implements schema::schema_definition.
References schema::field_info::fully_qualified_type, schema::field_info::is_repeated, schema::field_info::name, schema::field_info::tag, and schema::field_info::type.
                     {
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   if (field.type != schema::field_type::enum_type) {
     throw std::invalid_argument("Wrong field type");
   }
   google::protobuf::DescriptorProto* dpr = messages[message_id];
   if (dpr == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   google::protobuf::FieldDescriptorProto* field_proto = dpr->add_field();
   field_proto->set_name(field.name);
   field_proto->set_type(google::protobuf::FieldDescriptorProto_Type_TYPE_ENUM);
   field_proto->set_number(field.tag);
   field_proto->set_type_name(field.fully_qualified_type);
   if (field.is_repeated) {
     field_proto->set_label(
         google::protobuf::FieldDescriptorProto_Label_LABEL_REPEATED);
   }
 }
add_enum_value()
void protobuf_schema_definition::add_enum_value (int enum_id, const std::string & value_name, int value) virtual
Used to add values to an already created enum with enum_id. If such enum doesn't exist, exception will be thrown. TODO(kari): Decide if duplicate values are allowed.
Implements schema::schema_definition.
{
   if (enum_id < 0 || enum_id >= enums.size()) {
     throw std::out_of_range("No enum with id: " + std::to_string(enum_id));
   }
   google::protobuf::EnumDescriptorProto* edp = enums[enum_id];
   if (edp == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   google::protobuf::EnumValueDescriptorProto* field = edp->add_value();
   field->set_name(value_name);
   field->set_number(value);
 }
add_message()
void protobuf_schema_definition::add_message (int message_id) virtual
Used to add an already created message/enum schema to this schema. The message/enum should first be created and ready (fields/ nested messages/ enums or enum values must be added) before calling this function. Enum can be added to another message and if no message_id is provided in add_enum or message_id = -1, enum will be added globally. If message/enum with the given id doesn't exist, exception will be thrown.
Implements schema::schema_definition.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   if (messages[message_id] == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   google::protobuf::DescriptorProto* m =
       file_descriptor_proto->add_message_type();
   m->CopyFrom(*messages[message_id]);
 }
add_message_field()
void protobuf_schema_definition::add_message_field (schema::field_info field, int message_id) virtual
Implements schema::schema_definition.
References schema::field_info::fully_qualified_type, schema::field_info::is_repeated, schema::field_info::name, schema::field_info::tag, and schema::field_info::type.
                     {
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   if (field.type != schema::field_type::message_type) {
     throw std::invalid_argument("Wrong field type");
   }
   google::protobuf::DescriptorProto* dpr = messages[message_id];
   if (dpr == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   google::protobuf::FieldDescriptorProto* field_proto = dpr->add_field();
   field_proto->set_name(field.name);
   field_proto->set_type(
       google::protobuf::FieldDescriptorProto_Type_TYPE_MESSAGE);
   field_proto->set_number(field.tag);
   field_proto->set_type_name(field.fully_qualified_type);
   if (field.is_repeated) {
     field_proto->set_label(
         google::protobuf::FieldDescriptorProto_Label_LABEL_REPEATED);
   }
 }
add_nested_message()
void protobuf_schema_definition::add_nested_message (int message_id, int sub_message_id) virtual
Used to add nested message. Both messages must already exist. If any of them doesn't exist, exception will be thrown. The message with id sub_message_id will be added as a nested message to the other. Nested message is different from message field. It is like an inner class, NOT like a reference to an object *** TODO(kari): Check for name collisions TODO(kari): Decide if duplicate values are allowed.
Implements schema::schema_definition.
{
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   if (sub_message_id < 0 || sub_message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   if (messages[message_id] == NULL || messages[sub_message_id] == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   google::protobuf::DescriptorProto* dpr = messages[message_id];
   google::protobuf::DescriptorProto* m = dpr->add_nested_type();
   m->CopyFrom(*messages[sub_message_id]);
 }
add_scalar_field()
void protobuf_schema_definition::add_scalar_field (schema::field_info field, int message_id) virtual
These functions are called to add fields to a message. Any of them can be called multiple times on the same message. If the given message_id is not valid or the given field doesn't match the expected field type (ex. add_message_field() is called but the provided field is scalar type), exception will be thrown.
Implements schema::schema_definition.
References schema::field_info::is_repeated, schema::field_info::name, schema::field_info::tag, schema::field_info::type, and protobuf_schema::type_to_protobuf_type.
                     {
   if (message_id < 0 || message_id >= messages.size()) {
     throw std::out_of_range("No message with id: "
         + std::to_string(message_id));
   }
   if (field.type == schema::field_type::message_type ||
       field.type == schema::field_type::enum_type ||
       field.type == schema::field_type::unknown) {
     throw std::invalid_argument("Wrong field type");
   }
   google::protobuf::DescriptorProto* dpr = messages[message_id];
   if (dpr == NULL) {
     throw std::runtime_error("Unexpected error");
   }
   google::protobuf::FieldDescriptorProto* field_proto = dpr->add_field();
   field_proto->set_name(field.name);
   field_proto->set_type(protobuf_schema::type_to_protobuf_type.at(field.type));
   field_proto->set_number(field.tag);
   if (field.is_repeated) {
     field_proto->set_label(
         google::protobuf::FieldDescriptorProto_Label_LABEL_REPEATED);
   }
 }
create_enum()
int protobuf_schema_definition::create_enum (const std::string & enum_name) virtual
Returns the id of the created enum_schema. TODO(kari): Check for name collisions. Only creates empty enum schema and name it. Values should be added to the enum (using add_enum_value) and then add_enum() so the created enum schema is added to the schema.
Implements schema::schema_definition.
{
   enums.push_back(google::protobuf::Arena::Create<
       google::protobuf::EnumDescriptorProto>(&arena));
   enums[enums.size() - 1]->set_name(enum_name);
   return enums.size() - 1;
 }
create_message()
int protobuf_schema_definition::create_message (const std::string & message_name) virtual
Returns the id of the created message_schema. TODO(kari): Check for name collisions. Only creates empty message schema and name it. Fields and/or nested enums/messages should be added to the message (using add_* and add_*_field) and then add_message() so the created message schema is added to the schema.
Implements schema::schema_definition.
                   {
   messages.push_back(google::protobuf::Arena::Create<
       google::protobuf::DescriptorProto>(&arena));
   messages[messages.size() - 1]->set_name(message_name);
   return messages.size() - 1;
 }
get_descriptor()
google::protobuf::FileDescriptorProto * protobuf_schema_definition::get_descriptor ()
This function is used from protobuf_schema on import. (Instead of friend class)
{
         return file_descriptor_proto;
 }
register_self()
void protobuf_schema_definition::register_self ()
References protobuf_schema_definition(), and schema::schema_definition::register_factory().
{
   protobuf_schema_definition::register_factory("protobuf", [] {
       return reinterpret_cast<schema_definition*>
           (new protobuf_schema_definition());
   });
 }
The documentation for this class was generated from the following files:
protobuf_schema.h
protobuf_schema.cc