Automaton Core: RIPEMD160_cryptopp Class Reference
RIPEMD160_cryptopp Class Reference
#include <RIPEMD160_cryptopp.h>
Public Member Functions
RIPEMD160_cryptopp ()
void calculate_digest (const unsigned char *input, const size_t length, unsigned char *digest)
unsigned int digest_size () const
void final (unsigned char *digest)
void restart ()
void update (const unsigned char *input, const size_t length)
Static Public Member Functions
static bool register_self ()
Static Public Member Functions inherited from hash_transformation
static hash_transformation * create (const std::string name)
static void register_factory (std::string name, factory_function_type func)
Additional Inherited Members
Public Types inherited from hash_transformation
typedef hash_transformation *(* factory_function_type) ()
Constructor & Destructor Documentation
RIPEMD160_cryptopp()
RIPEMD160_cryptopp::RIPEMD160_cryptopp ()
Referenced by register_self().
{
   hash = new CryptoPP::RIPEMD160;
 }
Member Function Documentation
calculate_digest()
void RIPEMD160_cryptopp::calculate_digest (const unsigned char * input, const size_t length, unsigned char * digest) virtual
Reimplemented from hash_transformation.
{
   hash->CalculateDigest(digest, input, length);
 }
digest_size()
unsigned int RIPEMD160_cryptopp::digest_size () const virtual
Implements hash_transformation.
{
   return _digest_size;
 }
final()
void RIPEMD160_cryptopp::final (unsigned char * digest) virtual
Implements hash_transformation.
{
   hash->Final(digest);
 }
register_self()
bool RIPEMD160_cryptopp::register_self () static
References hash_transformation::register_factory(), and RIPEMD160_cryptopp().
{
   hash_transformation::register_factory("RIPEMD160",
   [] {return reinterpret_cast<hash_transformation*>
       (new RIPEMD160_cryptopp()); });
   return true;
 }
restart()
void RIPEMD160_cryptopp::restart () virtual
Implements hash_transformation.
{
   hash->Restart();
 }
update()
void RIPEMD160_cryptopp::update (const unsigned char * input, const size_t length) virtual
Implements hash_transformation.
{
   hash->Update(input, length);
 }
The documentation for this class was generated from the following files:
RIPEMD160_cryptopp.h
RIPEMD160_cryptopp.cc