Automaton Core: acceptor::acceptor_handler Class Reference
acceptor::acceptor_handler Class Reference abstract
#include <acceptor.h>
Public Member Functions
virtual void on_connected (connection *c, const std::string &address)=0
virtual void on_error (connection::error e)=0
virtual bool on_requested (const std::string &address)=0
Detailed Description
Handler class used to inform the client for events.
on_requested will be invoked when a peer wants to connect; it passes the address of the remote peer.
on_connected will be invoked if the connection was accepted by the peer and connection was made; it passes the resulting connection or null if no connection was made;
on_error will be invoked when an error happens while listening or accepting.
Member Function Documentation
on_connected()
virtual void acceptor::acceptor_handler::on_connected (connection * c, const std::string & address) pure virtual
Referenced by tcp_acceptor::start_accepting().
on_error()
virtual void acceptor::acceptor_handler::on_error (connection::error e) pure virtual
Referenced by tcp_acceptor::start_accepting().
on_requested()
virtual bool acceptor::acceptor_handler::on_requested (const std::string & address) pure virtual
Referenced by tcp_acceptor::start_accepting().
The documentation for this class was generated from the following file:
acceptor.h