Automaton Core: tcp_connection Class Reference
tcp_connection Class Reference
#include <tcp_implementation.h>
Public Member Functions
tcp_connection (const std::string &address_, connection_handler *handler_)
tcp_connection (const std::string &address_, const boost::asio::ip::tcp::socket &socket_, connection_handler *handler_)
~tcp_connection ()
void add_handler (connection_handler *handler_)
void async_read (char *buffer, unsigned int buffer_size, unsigned int num_bytes, unsigned int id)
void async_send (const std::string &msg, unsigned int id)
void connect ()
void disconnect ()
std::string get_address () const
connection::state get_state () const
Additional Inherited Members
Public Types inherited from connection
enum error {
no_error = 0, unknown = 1, invalid_address = 2, closed_by_peer = 3,
connection_refused = 4, timed_out = 5, broken_pipe = 6
}
typedef connection *(* factory_function) (const std::string &address, connection_handler *handler)
enum state { invalid_state = 0, connecting = 1, connected = 2, disconnected = 3 }
Static Public Member Functions inherited from connection
static connection * create (const std::string &type, const std::string &address, connection_handler *handler)
static void register_connection_type (const std::string &type, factory_function func)
Protected Member Functions inherited from connection
connection (connection_handler *handler_)
Protected Attributes inherited from connection
connection_handler * handler
Detailed Description
Class that represents a connection with a remote peer.
Constructor & Destructor Documentation
tcp_connection() [1/2]
tcp_connection::tcp_connection (const std::string & address_, connection_handler * handler_)
Constructor that will be used when this class is registered.
References asio_io_service.
              :connection(handler_), asio_socket{asio_io_service} {
   address = address_;
   boost::system::error_code boost_error_code;
   boost::asio::ip::tcp::resolver resolver{asio_io_service};
   std::string ip, port;
   parse_address(address_, &ip, &port);
   boost::asio::ip::tcp::resolver::query q{ip, port};
   asio_endpoint = *resolver.resolve(q, boost_error_code);
   if (boost_error_code) {
     logging("ERROR (in connection constructor): " + boost_error_code.message());
     handler_->on_error(this, connection::error::invalid_address);
   } else {
     logging("In connection constructor: successfully resolved address, "
     "no connection was made yet");
   }
 }
tcp_connection() [2/2]
tcp_connection::tcp_connection (const std::string & address_, const boost::asio::ip::tcp::socket & socket_, connection_handler * handler_)
Constructor that will be used from the acceptor.
                                                              :
     connection(handler_),
     asio_socket(std::move(const_cast<boost::asio::ip::tcp::socket&>(sock))),
     address(addr) {
 }
~tcp_connection()
tcp_connection::~tcp_connection ()
Destructor.
References logging().
{
   boost::system::error_code boost_error_code;
   asio_socket.shutdown(boost::asio::ip::tcp::socket::shutdown_both,
       boost_error_code);
   if (boost_error_code) {
     logging("ERROR (while destroying connection): " +
         boost_error_code.message());
   }
   asio_socket.close();
 }
Member Function Documentation
add_handler()
void tcp_connection::add_handler (connection_handler * handler_)
This function is used to change the handler. It may be necessary when a connection is created from the acceptor and the default handler (the one passed to the acceptor) needs to be changed.
References connection::handler.
{
   this->handler = handler_;
 }
async_read()
void tcp_connection::async_read (char * buffer, unsigned int buffer_size, unsigned int num_bytes, unsigned int id) virtual
If you call this function more than once, events form a queue, no read is cancelled
Implements connection.
References connection::handler, logging(), connection::connection_handler::on_disconnected(), connection::connection_handler::on_error(), connection::connection_handler::on_message_received(), and tcp_initialized.
{
   if (tcp_initialized && asio_socket.is_open()) {
     if (num_bytes <= 0) {
       asio_socket.async_read_some(boost::asio::buffer(buffer, buffer_size),
           [this, buffer, id](const boost::system::error_code& boost_error_code,
           size_t bytes_transferred) {
         if (boost_error_code) {
           if (boost_error_code == boost::asio::error::eof) {
             handler->on_disconnected(this);
             return;
           } else if (boost_error_code ==
                 boost::asio::error::operation_aborted) {
             return;
           } else {
             logging("ERROR (in async_read() 0): " +
                 boost_error_code.message());
             handler->on_error(this, connection::error::unknown);
             // TODO(kari): what errors and when should read be called?
           }
         } else {
           handler->on_message_received(this, buffer, bytes_transferred, id);
         }
       });
     } else {
         boost::asio::async_read(asio_socket,
           boost::asio::buffer(buffer, buffer_size),
           boost::asio::transfer_exactly(num_bytes),
           [this, buffer, id](const boost::system::error_code& boost_error_code,
           size_t bytes_transferred) {
         if (boost_error_code) {
           if (boost_error_code == boost::asio::error::eof) {
             handler->on_disconnected(this);
             return;
           } else if (boost_error_code ==
               boost::asio::error::operation_aborted) {
             return;
           } else {
             logging("ERROR (in async_read() 1): " +
                 boost_error_code.message());
             handler->on_error(this, connection::error::unknown);
             // TODO(kari): what errors and when should read be called?
           }
         } else {
           handler->on_message_received(this, buffer, bytes_transferred, id);
         }
       });
     }
   } else if (!tcp_initialized) {
     logging("ERROR (in start_listening() 1): Not initialized");
     handler->on_error(this, connection::error::unknown);
     // TODO(kari): what to do here? needs to be connected
   } else {
     logging("ERROR (in start_listening() 2): Socket closed");
     handler->on_error(this, connection::error::closed_by_peer);
   }
 }
async_send()
void tcp_connection::async_send (const std::string & msg, unsigned int id) virtual
This function is used for sending messages to the peer. It is asynchronous and the handler's function on_message_sent() will be called after the message was successfully sent or if an error occurred.
Implements connection.
References connection::handler, logging(), connection::connection_handler::on_message_sent(), and tcp_initialized.
{
   if (tcp_initialized && asio_socket.is_open() && msg.size() > 0) {
     std::string* message = new std::string(msg);
     asio_socket.async_write_some(boost::asio::buffer(*message),
         [this, id, message](const boost::system::error_code& boost_error_code,
         size_t bytes_transferred) {
       if (boost_error_code) {
         logging("ERROR (in async_send() 0): " + boost_error_code.message());
         if (boost_error_code == boost::asio::error::broken_pipe) {
           handler->on_message_sent(this, id, connection::error::closed_by_peer);
           // TODO(kari): ?? handle
         } else {
           handler->on_message_sent(this, id, connection::error::unknown);
         }
        // if (bytes_transferred < message.size())
       } else {
         handler->on_message_sent(this, id, connection::error::no_error);
       }
       delete message;
     });
   } else if (!tcp_initialized) {
     logging("ERROR (in async_send() 1): Not initialized");
     // handler->on_error(this, connection::error::unknown);
     handler->on_message_sent(this, id, connection::error::unknown);
     // TODO(kari): what to do here? needs to be connected
   } else {
     logging("ERROR (in async_send() 2): Socket closed");
     // handler->on_error(this, connection::error::closed_by_peer);
     handler->on_message_sent(this, id, connection::error::closed_by_peer);
   }
 }
connect()
void tcp_connection::connect () virtual
This function is used in the constructor. It is used to start async_connect with the peer. It can be used outside the constructor if the connection didn't happen or was closed or if disconnect() was first used. If a successful connection was made, start_listening() and handler's on_connected() will be called.
Implements connection.
References connection::handler, logging(), connection::connection_handler::on_connected(), connection::connection_handler::on_error(), and tcp_initialized.
{
   if (tcp_initialized) {
     // TODO(kari): if already connected {}
     asio_socket.async_connect(asio_endpoint,
         [this](const boost::system::error_code& boost_error_code) {
       if (boost_error_code) {
           logging("ERROR (in connect() 0): " + boost_error_code.message());
           if (boost_error_code == boost::asio::error::connection_refused) {
             handler->on_error(this, connection::error::connection_refused);
           } else {
             handler->on_error(this, connection::error::unknown);
           }
         } else {
           handler->on_connected(this);
         }
     });
   } else {
     logging("ERROR (in connect() 1): Not initialized! tcp_init() must be called"
        "first");
     handler->on_error(this, connection::error::unknown);
     // TODO(kari): what to do here? needs to be connected
   }
 }
disconnect()
void tcp_connection::disconnect () virtual
This function can be called to disconnect peer. To reconnect connect() shoul be called. Handler's on_disconnected() is called on successful disconnect, on_error(), otherwise.
Implements connection.
References connection::handler, logging(), connection::connection_handler::on_disconnected(), and connection::connection_handler::on_error().
{
   if (asio_socket.is_open()) {
     boost::system::error_code boost_error_code_shut;
     asio_socket.shutdown(boost::asio::ip::tcp::socket::shutdown_both,
         boost_error_code_shut);
     if (boost_error_code_shut) {
       handler->on_error(this, connection::error::unknown);
       logging("ERROR (in disconnect() 0): " + boost_error_code_shut.message());
     }
     boost::system::error_code boost_error_code_close;
     asio_socket.close(boost_error_code_close);
     if (boost_error_code_close) {
       handler->on_error(this, connection::error::unknown);
       logging("ERROR (in disconnect() 1): " + boost_error_code_close.message());
     }
   }
   handler->on_disconnected(this);
 }
get_address()
std::string tcp_connection::get_address () const virtual
Implements connection.
{
   return address;
 }
get_state()
connection::state tcp_connection::get_state () const virtual
Implements connection.
{
   // TODO(kari): implement this
   return connection::state::invalid_state;
 }
The documentation for this class was generated from the following files:
tcp_implementation.h
tcp_implementation.cc