Automaton Core: secp256k1_cryptopp Class Reference
secp256k1_cryptopp Class Reference
#include <secp256k1_cryptopp.h>
Public Member Functions
void gen_public_key (const unsigned char *private_key, unsigned char *public_key)
bool has_deterministic_signatures ()
size_t k_size ()
size_t private_key_size ()
size_t public_key_size ()
void sign (const unsigned char *private_key, const unsigned char *message, const size_t msg_len, unsigned char *signature)
void sign_deterministic (const unsigned char *private_key, const unsigned char *message, const size_t msg_len, const unsigned char *k, unsigned char *signature)
size_t signature_size ()
bool verify (const unsigned char *public_key, const unsigned char *message, const size_t msg_len, unsigned char *signature)
Static Public Member Functions
static bool register_self ()
Static Public Member Functions inherited from digital_signature
static digital_signature * create (std::string name)
static void register_factory (std::string name, digital_signature_factory_function func)
Additional Inherited Members
Public Types inherited from digital_signature
typedef digital_signature *(* digital_signature_factory_function) ()
Member Function Documentation
gen_public_key()
void secp256k1_cryptopp::gen_public_key (const unsigned char * private_key, unsigned char * public_key) virtual
Implements digital_signature.
References private_key_size().
{
   // Create private key object from exponent
   const CryptoPP::Integer privateExponent(private_key, private_key_size());
   CryptoPP::ECDSA<CryptoPP::ECP, CryptoPP::SHA256>::PrivateKey privateKey;
   privateKey.Initialize(CryptoPP::ASN1::secp256k1(), privateExponent);
   // Create the public key object
   CryptoPP::ECDSA<CryptoPP::ECP, CryptoPP::SHA256>::PublicKey publicKey;
   privateKey.MakePublicKey(publicKey);
   // Save the public key in public_key
   publicKey.GetGroupParameters().GetCurve().EncodePoint(public_key,
       publicKey.GetPublicElement(), true);
 }
has_deterministic_signatures()
bool secp256k1_cryptopp::has_deterministic_signatures () virtual
Implements digital_signature.
{
   return false;
 }
k_size()
size_t secp256k1_cryptopp::k_size () virtual
Implements digital_signature.
{
   return 0;
 }
private_key_size()
size_t secp256k1_cryptopp::private_key_size () virtual
Implements digital_signature.
Referenced by gen_public_key(), and sign().
{
   return 32;
 }
public_key_size()
size_t secp256k1_cryptopp::public_key_size () virtual
Implements digital_signature.
Referenced by verify().
{
   return 33;
 }
register_self()
bool secp256k1_cryptopp::register_self () static
References digital_signature::register_factory().
{
   secp256k1_cryptopp::register_factory("secp256k1", [] {
     return reinterpret_cast<digital_signature*>(new secp256k1_cryptopp());
   });
   return true;
 }
sign()
void secp256k1_cryptopp::sign (const unsigned char * private_key, const unsigned char * message, const size_t msg_len, unsigned char * signature) virtual
Implements digital_signature.
References private_key_size(), and signature_size().
{
   CryptoPP::AutoSeededRandomPool prng;
   std::string str_signature;
   // Create private key object from exponent
   const CryptoPP::Integer privateExponent(private_key, private_key_size());
   // TODO(Samir): Need to use identity hash intead of SHA256
   CryptoPP::ECDSA<CryptoPP::ECP, CryptoPP::SHA256>::PrivateKey privateKey;
   privateKey.Initialize(CryptoPP::ASN1::secp256k1(), privateExponent);
   memset(signature, 0, signature_size());
   CryptoPP::StringSource(message, msg_len, true,
     new CryptoPP::SignerFilter(prng, CryptoPP::ECDSA<CryptoPP::ECP,
         CryptoPP::SHA256>::Signer(privateKey),
             new CryptoPP::ArraySink(signature, signature_size())));
   // std::cout << "signature length: " << str_signature.length() << std::endl;
   // std::cout << "signature: " << str_signature << std::endl;
 }
sign_deterministic()
void secp256k1_cryptopp::sign_deterministic (const unsigned char * private_key, const unsigned char * message, const size_t msg_len, const unsigned char * k, unsigned char * signature) virtual
Implements digital_signature.
{
   throw;
 }
signature_size()
size_t secp256k1_cryptopp::signature_size () virtual
Implements digital_signature.
Referenced by sign(), and verify().
{
   return 64;
 }
verify()
bool secp256k1_cryptopp::verify (const unsigned char * public_key, const unsigned char * message, const size_t msg_len, unsigned char * signature) virtual
Implements digital_signature.
References public_key_size(), and signature_size().
{
   CryptoPP::ECDSA<CryptoPP::ECP, CryptoPP::SHA256>::PublicKey publicKey;
   std::string input(reinterpret_cast<const char*>(public_key),
       public_key_size());
   CryptoPP::ECP::Point p;
   publicKey.AccessGroupParameters().Initialize(CryptoPP::ASN1::secp256k1());
   publicKey.GetGroupParameters().GetCurve().DecodePoint(p, public_key,
       public_key_size());
   publicKey.SetPublicElement(p);
   // TODO(Samir): Change SHA256 to identity hash
   CryptoPP::ECDSA<CryptoPP::ECP, CryptoPP::SHA256>::Verifier
       verifier(publicKey);
   return verifier.VerifyMessage(message, msg_len, signature,
       signature_size());
 }
The documentation for this class was generated from the following files:
secp256k1_cryptopp.h
secp256k1_cryptopp.cc