Automaton Core: state_impl Class Reference
state_impl Class Reference
#include <state_impl.h>
Public Member Functions
state_impl (hash_transformation *hasher)
void commit_changes ()
void delete_node_tree (const std::string &path)
void discard_changes ()
void erase (const std::string &path)
std::string get (const std::string &key)
std::vector< std::string > get_node_children (const std::string &path)
std::string get_node_hash (const std::string &path)
uint32_t hash_size ()
void print_subtrie (std::string path, std::string formated_path)
void set (const std::string &key, const std::string &value)
uint32_t size ()
Constructor & Destructor Documentation
state_impl()
state_impl::state_impl (hash_transformation * hasher) explicit
{
   nodes.push_back(state_impl::node());
   this->hasher = hasher;
   nodes_current_state = 1;
   calculate_hash(0);
   permanent_nodes_count = 1;
 }
Member Function Documentation
commit_changes()
void state_impl::commit_changes () virtual
Implements state.
{
   // Erase backups
   backup.clear();
   if (free_locations.empty()) {
     permanent_nodes_count = nodes.size();
     return;
   }
   // If we have fragmented, move not deleted elements from
   // the end of the vector into them
   auto it_low = free_locations.begin();
   auto rit_high = free_locations.rbegin();
   uint32_t empty_elements = free_locations.size();
   uint32_t last_element = nodes.size() - 1;
   // Copy elements and skip if element is deleted
   while (*it_low != *rit_high) {
   // auto it_last_element = free_locations.find(last_element);
     if (last_element == *rit_high) {
       rit_high++;
     } else {
       nodes[*it_low] = nodes[last_element];
       uint32_t parent = nodes[last_element].parent;
       uint8_t path_from_parent = nodes[last_element].prefix[0];
       nodes[parent].children[path_from_parent] = *it_low;
       it_low++;
     }
     last_element--;
   }
   nodes[*it_low] = nodes[last_element];
   nodes.resize(nodes.size() - empty_elements);
   permanent_nodes_count = nodes.size();
   free_locations.clear();
 }
delete_node_tree()
void state_impl::delete_node_tree (const std::string & path) virtual
Implements state.
References tohex().
{
   // TODO(Samir): Implement delete subtrie ( subtrie of node with value only? )
   int32_t cur_node = get_node_index(path);
   if (cur_node == -1 || nodes[cur_node].value == "") {
     throw std::out_of_range("No set node at path: " + tohex(path));
   }
   backup_nodes(nodes[cur_node].parent);
   subtrie_mark_free(cur_node);
   std::vector<unsigned char> children;
   unsigned char i = 0;
   uint32_t parent = nodes[cur_node].parent;
   unsigned char path_from_parent = nodes[cur_node].prefix[0];
   nodes[parent].children[path_from_parent] = 0;
   free_locations.insert(cur_node);
   // move_last_element_to(cur_node);
   // Find out how many children does the parent have
   children.clear();
   cur_node = parent;
   // TODO(Samir): add this and all child nodes to fragmented locations
   do {
     if (nodes[cur_node].children[i]) {
       children.push_back(i);
     }
   } while (++i != 0);
   // If the parent of the deleted node has no prefix, has only one
   // child remaining and is not the root we will merge it with his child
   if (nodes[cur_node].value.length() == 0
     && children.size() == 1 && cur_node != 0) {
     parent = nodes[cur_node].parent;
     uint32_t child = nodes[cur_node].children[children[0]];
     backup_nodes(child);
     nodes[child].prefix.insert(0, nodes[cur_node].prefix);
     // link parent and child
     path_from_parent = nodes[cur_node].prefix[0];
     nodes[parent].children[path_from_parent] = child;
     nodes[child].parent = parent;
     free_locations.insert(cur_node);
     // add_fragmented_location(cur_node);
     // move_last_element_to(cur_node);
     cur_node = child;
   }
   calculate_hash(cur_node);
 }
discard_changes()
void state_impl::discard_changes () virtual
Implements state.
{
   for (auto it = backup.begin(); it != backup.end(); ++it) {
     nodes[it->first] = it->second;
   }
   nodes.resize(permanent_nodes_count);
   free_locations.clear();
 }
erase()
void state_impl::erase (const std::string & path) virtual
Implements state.
References tohex().
Referenced by set().
{
   int32_t cur_node = get_node_index(path);
   if (cur_node == -1 || nodes[cur_node].value == "") {
     throw std::out_of_range("No set node at path: " + tohex(path));
   }
   backup_nodes(cur_node);
   // Get the children of this node
   std::vector<unsigned char> children;
   unsigned char i = 0;
   do {
     if (nodes[cur_node].children[i]) {
       children.push_back(i);
     }
   } while (++i != 0);
   // If multiple children just erase the value
   if (children.size() > 1) {
     nodes[cur_node].value = "";
   // If one child -> merge prefix into child, link parent and child
   } else if (children.size() == 1) {
     uint32_t parent = nodes[cur_node].parent;
     uint32_t child = nodes[cur_node].children[children[0]];
     // backup the child before chaning it
     backup_nodes(child);
     // add the prefix of current node to the child
     nodes[child].prefix.insert(0, nodes[cur_node].prefix);
     // link parent and child
     unsigned char path_from_parent = nodes[cur_node].prefix[0];
     nodes[parent].children[path_from_parent] = child;
     nodes[child].parent = parent;
     // Remember empty elements for later use
     free_locations.insert(cur_node);
     // move_last_element_to(cur_node);
     cur_node = child;
   // If no child -> remove element and handle parent cases
   } else {
     // erase the link from parent
     uint32_t parent = nodes[cur_node].parent;
     unsigned char path_from_parent = nodes[cur_node].prefix[0];
     nodes[parent].children[path_from_parent] = 0;
     free_locations.insert(cur_node);
     // move_last_element_to(cur_node);
     // Find out how many children does the parent have
     children.clear();
     cur_node = parent;
     unsigned char i = 0;
     do {
       if (nodes[cur_node].children[i]) {
         children.push_back(i);
       }
     } while (++i != 0);
     // If the parent of the deleted node has no prefix, has only one
     // child remaining and is not the root we will merge it with his child
     if (nodes[cur_node].value.length() == 0
         && children.size() == 1 && cur_node != 0) {
       parent = nodes[cur_node].parent;
       uint32_t child = nodes[cur_node].children[children[0]];
       backup_nodes(child);
       nodes[child].prefix.insert(0, nodes[cur_node].prefix);
       // link parent and child
       path_from_parent = nodes[cur_node].prefix[0];
       nodes[parent].children[path_from_parent] = child;
       nodes[child].parent = parent;
       free_locations.insert(cur_node);
       // move_last_element_to(cur_node);
       cur_node = child;
     }
   }
   calculate_hash(cur_node);
 }
get()
std::string state_impl::get (const std::string & key) virtual
Implements state.
{
   int32_t node_index = get_node_index(key);
   //  std::cout << "index at key\"" << key << "\": " << node_index << std::endl;
   return node_index == -1 ? "" : nodes[node_index].value;
 }
get_node_children()
std::vector< std::string > state_impl::get_node_children (const std::string & path) virtual
Implements state.
Referenced by print_subtrie().
{
   std::vector<std::string> result;
   int32_t node_index = get_node_index(path);
   if (node_index == -1) {
     throw std::out_of_range("No node at this path");
   }
   unsigned char i = 0;
   do {
     if (nodes[node_index].children[i]) {
       uint32_t child = nodes[node_index].children[i];
       // TODO(Samir): potential bug ( big vs little endian)
       result.push_back(std::string(nodes[child].prefix));
     }
   } while (++i != 0);
   return result;
 }
get_node_hash()
std::string state_impl::get_node_hash (const std::string & path) virtual
Implements state.
Referenced by print_subtrie().
{
   int32_t node_index = get_node_index(path);
   return node_index == -1 ? "" : nodes[node_index].hash;
 }
hash_size()
uint32_t state_impl::hash_size () virtual
Implements state.
References hash_transformation::digest_size().
{
   return hasher->digest_size();
 }
print_subtrie()
void state_impl::print_subtrie (std::string path, std::string formated_path)
References get_node_children(), get_node_hash(), and tohex().
{
   std::cout << formated_path << " prefix: " <<
       tohex(nodes[get_node_index(path)].prefix) << " value: " << get(path)
       << " hash: " << tohex(get_node_hash(path)) << std::endl << std::endl;
   std::vector<std::string> children = get_node_children(path);
   for (auto i : children) {
     print_subtrie(path + i, formated_path + "/" + tohex(i));
   }
 }
set()
void state_impl::set (const std::string & key, const std::string & value) virtual
Implements state.
References erase().
{
   if (value == "") {
     erase(key);
     return;
   }
   uint32_t cur_node = 0;
   uint32_t cur_prefix_index = 0;
   unsigned int i = 0;
   for (; i < key.length(); ++i) {
     unsigned char path_element = key[i];
     if (cur_prefix_index == nodes[cur_node].prefix.length()) {
       // If there is no prefix or there is prefix but we have reached the end
       if (nodes[cur_node].children[path_element] != 0) {
         // If there is child with the next path element continue on the path
         cur_node = nodes[cur_node].children[path_element];
       } else if (has_children(cur_node) ||
           nodes[cur_node].value != "" || cur_node == 0) {
         // This node has children, value set or is the root.
         // It can't be the final node.
         backup_nodes(cur_node);
         cur_node = add_node(cur_node, path_element);
       } else {
         // this node has no children so it's the final node. The remainder
         // of the path will be the prefix including the path from parent
         nodes[cur_node].prefix.append(key.substr(i));
         break;
       }
       cur_prefix_index = 1;
     // If there is prefix at this node -> progress prefix
     } else {
       // If next path element does not match the next prefix element,
       // create a split node at the difference
       if (path_element !=
           (unsigned char)nodes[cur_node].prefix[cur_prefix_index]) {
         const std::string cur_node_prefix = nodes[cur_node].prefix;
         // Backup necesery nodes before changes
         backup_nodes(cur_node);
         // Create the split_node and set up links with cur_node
         uint32_t split_node = add_node(nodes[cur_node].parent,
             nodes[cur_node].prefix[0]);
         // Set split node as parent of cur_node
         nodes[cur_node].parent = split_node;
         // Set the current node as child of the new split node
         unsigned char path_to_child =
             (unsigned char)cur_node_prefix[cur_prefix_index];
         nodes[split_node].children[path_to_child] = cur_node;
         // set prefix of split_node and cur_node
         nodes[split_node].prefix = cur_node_prefix.substr(0, cur_prefix_index);
         nodes[cur_node].prefix = cur_node_prefix.substr(cur_prefix_index);
         // Recalculate the hash of the child part of the node that got split
         calculate_hash(cur_node);
         // Create the new node from the split to the next path element
         cur_node = add_node(split_node, path_element);
         cur_prefix_index = 1;
       } else {
         ++cur_prefix_index;
       }
     }
   }
   // We checked the whoel key but there is still prefix left.
   if ((nodes[cur_node].prefix.length() != cur_prefix_index)
       && i == key.length()) {
     backup_nodes(cur_node);
     const std::string cur_node_prefix = nodes[cur_node].prefix;
     // Create the split_node and set up links with cur_node
     uint32_t split_node = add_node(nodes[cur_node].parent,
         nodes[cur_node].prefix[0]);
     // Set split node as parent of cur_node
     nodes[cur_node].parent = split_node;
     // Set the current node as child of the new split node
     const unsigned char path_to_child = cur_node_prefix[cur_prefix_index];
     nodes[split_node].children[path_to_child] = cur_node;
     // set prefix of split_node and cur_node
     nodes[split_node].prefix = cur_node_prefix.substr(0, cur_prefix_index);
     nodes[cur_node].prefix = cur_node_prefix.substr(cur_prefix_index);
     // Recalculate the hash of the child part of the node that got split
     calculate_hash(cur_node);
     // Create the new node from the split to the next path element
     cur_node = split_node;
   }
   backup_nodes(cur_node);
   // set the value and calculate the hash
   nodes[cur_node].value = value;
   calculate_hash(cur_node);
 }
size()
uint32_t state_impl::size ()
{
   return nodes.size();
 }
The documentation for this class was generated from the following files:
state_impl.h
state_impl.cc