Automaton Core: ed25519_orlp Class Reference
ed25519_orlp Class Reference
#include <ed25519_orlp.h>
Public Member Functions
void gen_public_key (const unsigned char *private_key, unsigned char *public_key)
bool has_deterministic_signatures ()
size_t k_size ()
size_t private_key_size ()
size_t public_key_size ()
void sign (const unsigned char *private_key, const unsigned char *message, const size_t msg_len, unsigned char *signature)
void sign_deterministic (const unsigned char *private_key, const unsigned char *message, const size_t msg_len, const unsigned char *k, unsigned char *signature)
size_t signature_size ()
bool verify (const unsigned char *public_key, const unsigned char *message, const size_t msg_len, unsigned char *signature)
Static Public Member Functions
static bool register_self ()
Static Public Member Functions inherited from digital_signature
static digital_signature * create (std::string name)
static void register_factory (std::string name, digital_signature_factory_function func)
Additional Inherited Members
Public Types inherited from digital_signature
typedef digital_signature *(* digital_signature_factory_function) ()
Member Function Documentation
gen_public_key()
void ed25519_orlp::gen_public_key (const unsigned char * private_key, unsigned char * public_key) virtual
Implements digital_signature.
has_deterministic_signatures()
bool ed25519_orlp::has_deterministic_signatures () virtual
Implements digital_signature.
k_size()
size_t ed25519_orlp::k_size () virtual
Implements digital_signature.
private_key_size()
size_t ed25519_orlp::private_key_size () virtual
Implements digital_signature.
public_key_size()
size_t ed25519_orlp::public_key_size () virtual
Implements digital_signature.
register_self()
bool ed25519_orlp::register_self () static
References digital_signature::register_factory().
sign()
void ed25519_orlp::sign (const unsigned char * private_key, const unsigned char * message, const size_t msg_len, unsigned char * signature) virtual
Implements digital_signature.
Referenced by sign_deterministic().
sign_deterministic()
void ed25519_orlp::sign_deterministic (const unsigned char * private_key, const unsigned char * message, const size_t msg_len, const unsigned char * k, unsigned char * signature) virtual
Implements digital_signature.
References sign().
signature_size()
size_t ed25519_orlp::signature_size () virtual
Implements digital_signature.
verify()
bool ed25519_orlp::verify (const unsigned char * public_key, const unsigned char * message, const size_t msg_len, unsigned char * signature) virtual
Implements digital_signature.
The documentation for this class was generated from the following files:
ed25519_orlp.h
ed25519_orlp.cc