Automaton Core: state_impl.cc File Reference
state_impl.cc File Reference
#include "state/state_impl.h"
#include <map>
#include <algorithm>
#include <iomanip>
#include <string>
#include <sstream>
#include <vector>
#include <set>
#include <utility>
#include "crypto/hash_transformation.h"
Typedefs
typedef std::basic_string< unsigned char > ustring
Functions
static std::string tohex (std::string s)
Typedef Documentation
ustring
typedef std::basic_string<unsigned char> ustring
Function Documentation
tohex()
static std::string tohex (std::string s) static
Referenced by state_impl::delete_node_tree(), state_impl::erase(), and state_impl::print_subtrie().