Automaton Core: tcp_implementation.cc File Reference
tcp_implementation.cc File Reference
#include "network/tcp_implementation.h"
#include <mutex>
#include <regex>
#include <thread>
#include <boost/asio/read.hpp>
Functions
void logging (const std::string &s)
void parse_address (const std::string &address, std::string *result_addr, std::string *result_port)
void tcp_init ()
static boost::asio::io_service::work work_ (asio_io_service)
Variables
static boost::asio::io_service asio_io_service
static std::mutex console_mutex
static bool tcp_initialized = false
static std::thread * worker_thread
Function Documentation
logging()
void logging (const std::string & s)
References console_mutex.
Referenced by tcp_connection::async_read(), tcp_connection::async_send(), tcp_connection::connect(), tcp_connection::disconnect(), tcp_acceptor::start_accepting(), and tcp_connection::~tcp_connection().
{
   console_mutex.lock();
   std::cout << s << std::endl;
   console_mutex.unlock();
 }
parse_address()
void parse_address (const std::string & address, std::string * result_addr, std::string * result_port)
{
   std::regex rgx_ip("((?:\\d+\\.)+\\d+|(?:[0-9a-f]+:)+[0-9a-f]+):(\\d+)");
   std::smatch match;
   if (std::regex_match(address.begin(), address.end(), match, rgx_ip) &&
       match.size() == 3) {
     *result_addr = match[1];
     *result_port = match[2];
   } else {
     *result_addr = "";
     *result_port = "";
   }
 }
tcp_init()
void tcp_init ()
For now initializing asio io_service and work objects. New thread is created and io_service.run() called in it.
References asio_io_service, acceptor::register_acceptor_type(), connection::register_connection_type(), tcp_initialized, and worker_thread.
                 {
   if (tcp_initialized) {
     return;
   }
   connection::register_connection_type("tcp", [](const std::string& address,
     connection::connection_handler* handler) {
     return reinterpret_cast<connection*>(new tcp_connection(address, handler));
   });
   acceptor::register_acceptor_type("tcp", [](const std::string& address,
       acceptor::acceptor_handler* handler_, connection::connection_handler*
       connections_handler_) {
     return reinterpret_cast<acceptor*>(new tcp_acceptor(address, handler_,
       connections_handler_));
   });
   worker_thread = new std::thread([]() {
       asio_io_service.run();
   });
   tcp_initialized = true;
 }
work_()
static boost::asio::io_service::work work_ (asio_io_service) static
Variable Documentation
asio_io_service
boost::asio::io_service asio_io_service static
Referenced by tcp_acceptor::start_accepting(), tcp_acceptor::tcp_acceptor(), tcp_connection::tcp_connection(), and tcp_init().
console_mutex
std::mutex console_mutex static
Referenced by logging().
tcp_initialized
bool tcp_initialized = false static
Referenced by tcp_connection::async_read(), tcp_connection::async_send(), tcp_connection::connect(), tcp_acceptor::start_accepting(), and tcp_init().
worker_thread
std::thread* worker_thread static
Referenced by tcp_init().