Automaton Core: tcp_implementation.h File Reference
tcp_implementation.h File Reference
#include <iostream>
#include <string>
#include <vector>
#include <utility>
#include <memory>
#include <boost/asio/io_service.hpp>
#include <boost/asio/basic_stream_socket.hpp>
#include <boost/asio/write.hpp>
#include <boost/asio/error.hpp>
#include <boost/asio/buffer.hpp>
#include <boost/asio/ip/tcp.hpp>
#include "network/connection.h"
#include "network/acceptor.h"
Classes
class tcp_acceptor
class tcp_connection
Functions
void logging (const std::string &s)
void parse_address (const std::string &, std::string *result_addr, std::string *result_port)
void tcp_init ()
Function Documentation
logging()
void logging (const std::string & s)
References console_mutex.
Referenced by tcp_connection::async_read(), tcp_connection::async_send(), tcp_connection::connect(), tcp_connection::disconnect(), tcp_acceptor::start_accepting(), and tcp_connection::~tcp_connection().
parse_address()
void parse_address (const std::string & , std::string * result_addr, std::string * result_port)
tcp_init()
void tcp_init ()
For now initializing asio io_service and work objects. New thread is created and io_service.run() called in it.
References asio_io_service, acceptor::register_acceptor_type(), connection::register_connection_type(), tcp_initialized, and worker_thread.